name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install all dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      # (optional) then test or build the front end…
      - name: Build Frontend
        run: |
          cd frontend
          npm ci
          npm run build
